### ISSUE TITLE
output

### ISSUE THREAD

**Issue by AkramMohammadi** [vitords/HoeffdingTree#7]
Hi,Dear
it is output for HIGGS dataset, do you know correct by output?
Do you know what I can be doing wrong?

Thanks in advance.
_str nomodel
 (11010001.0)
Dataset 'New dataset'
   Attributes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28']
   Class attribute: 0
   Total instances: 10000
 (11010001.0)
Instance
   From dataset: New dataset
   Attribute values: ['0.00E+000', '5.47E-001 ', '-3.50E-001', '-6.47E-001', '2.04E+000', '2.76E-001', '5.45E-001', '8.39E-001', '1.73E+000', '0.00E+000', '6.53E-001', '1.47E+000', '1.24E+000', '0.00E+000', '7.86E-001', '-4.44E-002', '-1.02E+000', '2.55E+000', '4.19E-001', '-6.29E-001', '1.57E+000', '3.10E+000', '6.89E-001', '8.67E-001', '1.08E+000', '6.64E-001', '3.54E-001', '5.80E-001', '8.17E-001']
   Class: 0.00E+000 
[ ]

Process finished with exit code 0

**Comment by vitords** [comment]
Hello @AkramMohammadi,
by the looks of it, you're doing everything right. Your issue is most certainly with the number of instances (rows in your dataset, basically).

10000 is too small of a number for a data stream mining algorithm like this.
As a quick test, you can try multiply the number of instances (duplicate them, copy and paste, whatever you prefer) until you reach a value over 500k or even 1 million. You'll see your tree starting to taking form with that. If even after this you don't get a tree, then there's probably something wrong with either the dataset or the way you're feeding it to the algorithm.

**Comment by AkramMohammadi** [comment]
Thanks a lot .
data set is very big and have 11milimon record.but cant build tree model.
I need know how do the first build tree model and how can update with one instance?

**Comment by vitords** [comment]
I'd need to at least see your code and a sample of the dataset in the format you're using to help you any further. What have you tried? What is going wrong in training the model?

Here you can find an example of how the model can be trained: https://github.com/vitords/HoeffdingTree/blob/master/main.py
This should help you get started with the algorithm.

To update the model with a new instance, you have the ```HoeffdingTree.update_classifier``` method. See it here: https://github.com/vitords/HoeffdingTree/blob/master/hoeffdingtree.py#L115

**Comment by AkramMohammadi** [comment]
Hi vitords

I used to attached files for experiments but can`t get tree model.
I have another question: how to calculate "pre_dist" and "post_dist" properly for my dataset?


[main.txt](https://github.com/vitords/HoeffdingTree/files/1935507/main.txt)
dataset and main.txt send email`s
[dataset_file.txt](https://github.com/vitords/HoeffdingTree/files/1936757/dataset_file.txt)
