### ISSUE TITLE
a question about the code

### ISSUE THREAD

**Issue by RukawaKaede** [vitords/HoeffdingTree#9]
Hello, :-)
file ht/gaussianconditionalsufficientstats.py:
in the function "probability_density(self, value)", the code follows:
```
return (1.0 / (self.CONST * std_dev)) * math.exp(-(diff * diff / (2.0 * self._variance))) 
```
I think this code means the probability density function of Gaussian distribution, but the self.CONST here actually is ```math.log(2 * math.pi)```, should it be ```math.sqrt(2 * math.pi)```?
please point it out if I am wrong, thanks

**Comment by vitords** [comment]
Hey @RukawaKaede, sorry for the taking so long to address this issue.
To be quite frankly, I don't remember why the probability density is being calculated like that (I have a faint memory of it having something to do with a lognormal distribution, not too confident on that though). Maybe you can check it?

Also, have you tried using the square root to see how it behaves?

This whole code repository is long due to some serious refactoring and improvements, I just need to find time for it. If you have any contributions, feel free to open a PR!
